[workspace]
resolver = "3"
members = ["crates/fc-core", "crates/fc-gtk"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.88"

[workspace.dependencies]
fc-core = { path = "crates/fc-core" }
thiserror = "2"
tempfile = "3"
gtk = { package = "gtk4", version = "0.11", features = ["v4_20"] }

[workspace.lints.rust]
unsafe_code = "forbid"
